MVC_FinalDemo/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_FinalDemo.Models;
using MVC_FinalDemo.Models.Interface;
using MVC_FinalDemo.Models.Repository;

namespace MVC_FinalDemo.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository _productRepository;
        private ICategoryRepository _categoryRepository;
        private ICustomerRepository _customerRepository;
        private IOrderRepository _orderRepository;
        private IOrderDetailRepository _orderDetailRepository;
        public AdminController()
        {
            _productRepository = new ProductRepository();
            _categoryRepository = new CategoryRepository();
            _customerRepository = new CustomerRepository();
            _orderRepository = new OrderRepository();
            _orderDetailRepository = new OrderDetailRepository();
        }
        public List<SelectListItem> GetItem()
        {
            List<SelectListItem> ls = new List<SelectListItem>()
            {
                new SelectListItem{ Text="未出貨", Value="未出貨"},
                new SelectListItem{ Text="已出貨", Value="已出貨"},
                new SelectListItem{ Text="已到貨", Value="已到貨"},
                new SelectListItem{ Text="已付款", Value="已付款"}
            };

            return ls;
        }
        
        //dbEStoreEntities db = new dbEStoreEntities();
        ProductCategoryViewModel pcvm = new ProductCategoryViewModel();
        // GET: Admin
        [Authorize]
        public ActionResult Index()
        {
            if (User.Identity.Name == "root")
            {
                return View(_productRepository.GetAll());
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult Product(int id=1)
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            //var catName = db.tCatagory.Where(m => m.Id == id).FirstOrDefault();
            var catName = _categoryRepository.Get(id);
            //pcvm.Products = db.tProduct.Where(m => m.fProductCatagory == catName.fName).ToList();
            pcvm.Products = _productRepository.GetAllByCategory(catName.fName).ToList();
            //pcvm.Category = db.tCatagory.ToList();
            pcvm.Category = _categoryRepository.GetAll().ToList();
            return View(pcvm);

        }

        [Authorize]
        public ActionResult Category()
        {
            return View(_categoryRepository.GetAll().ToList());
        }

        [Authorize]
        public ActionResult CaCreate()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CaCreate(string fName)
        {
            //var cats = db.tCatagory.Where(m=>m.fName == fName).FirstOrDefault();
            var cats = _categoryRepository.GetByName(fName);
            //var count = db.tCatagory.ToList().Count();
            var count = _categoryRepository.GetAll().Count();
            var cid = "A";
            
            if (cats == null)
            {
                if (count < 10)
                {
                    cid += "0";
                }
                tCatagory cat = new tCatagory { 
                    fCatagoryID = cid + (++count),
                    fName = fName,
                };
                //db.tCatagory.Add(cat);
                _categoryRepository.Create(cat);
                //db.SaveChanges();
                return RedirectToAction("Category");
            }
            ViewBag.isCate = true;
            return View();
        }

        [Authorize]
        public ActionResult CaEdit(string cid)
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            //var catagory = db.tCatagory.Where(m=>m.fCatagoryID == cid).FirstOrDefault();
            var category = _categoryRepository.GetByCategoryID(cid);
            return View(category);
        }

        [Authorize]
        [HttpPost]
        public ActionResult CaEdit(string fCatagoryID, string oldName, string fName)
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            //var cats = db.tCatagory.Where(m=>m.fCatagoryID == fCatagoryID).FirstOrDefault();
            var cats = _categoryRepository.GetByCategoryID(fCatagoryID);
            cats.fName = fName;
            _categoryRepository.Update(cats);
            //var pds = db.tProduct.Where(m => m.fProductCatagory == oldName).ToList();
            var pds = _productRepository.GetAllByCategory(oldName).ToList();
            foreach (var pd in pds)
            {
                pd.fProductCatagory = fName;
                _productRepository.Update(pd);
            }
            //db.SaveChanges();
            
            _productRepository.SaveChanges();
            return RedirectToAction("Category");
        }

        [Authorize]
        public ActionResult Member()
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            return View(_customerRepository.GetAll());
        }

        [Authorize]
        public ActionResult CEdit(string cid)
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            //var cust = db.tCustomer.Where(m => m.fCustomerID == cid).FirstOrDefault();
            var cust = _customerRepository.GetByCustomerID(cid);
            return View(cust);
        }

        [Authorize]
        [HttpPost]
        public ActionResult CEdit(tCustomer cus)
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            _customerRepository.Update(cus);
            //db.Entry(cus).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            return RedirectToAction("Member");
        }

        [Authorize]
        public ActionResult CDelete(string cid)
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            //var cust = db.tCustomer.Where(m=>m.fCustomerID == cid).FirstOrDefault();
            var cust = _customerRepository.GetByCustomerID(cid);
            _customerRepository.Delete(cust);
            //db.Entry(cust).State = System.Data.Entity.EntityState.Deleted;
            //db.SaveChanges();
            return RedirectToAction("Member");
        }

        [Authorize]
        public ActionResult Order()
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Option = GetItem();
            return View(_orderRepository.GetAll().ToList());
        }


        [Authorize]
        public ActionResult ODelete( string oid)
        {
            //var odr = db.tOrder.Where(m=>m.fOrderID == oid).FirstOrDefault();
            var odr = _orderRepository.GetById(oid).FirstOrDefault();
            //var odt = db.tOrderDetail.Where(m => m.fOrderID == oid).ToList();
            var odt = _orderDetailRepository.GetById(oid).ToList();
            //db.tOrderDetail.RemoveRange(odt);
            _orderDetailRepository.DeleteRange(odt);
            //db.tOrder.Remove(odr);
            _orderRepository.Delete(odr);
            //db.SaveChanges();
            return RedirectToAction("Order");
        }

        [Authorize]
        public ActionResult PEdit(string pd)
        {
            if (User.Identity.Name != "root")
            {
                return RedirectToAction("Index", "Home");
            }
            //var product = db.tProduct.Where(m=>m.fProductName == pd).FirstOrDefault();
            var product = _productRepository.GetByName(pd);
            //ViewBag.Category = db.tCatagory.ToList();
            ViewBag.Category = _categoryRepository.GetAll();
            return View(product);
        }

        [Authorize]
        [HttpPost]
        public ActionResult PEdit(string fProductID, string fProductName, string fProductCatagory, int fProductPrice)
        {
            //var pd = db.tProduct.Where(m => m.fProductID == fProductID).FirstOrDefault();
            var pd = _productRepository.GetByProductID(fProductID);
            pd.fProductName = fProductName;
            pd.fProductCatagory = fProductCatagory;
            pd.fProductPrice = fProductPrice;
            //db.SaveChanges();
            _productRepository.SaveChanges();
            return RedirectToAction("Product", new { id = 1 }) ;
        }

        [Authorize]
        public ActionResult PDelete(string pd)
        {
            //var products = db.tProduct.Where(m => m.fProductName == pd).FirstOrDefault();
            var products = _productRepository.GetByName(pd);
            //db.tProduct.Remove(products);
            _productRepository.Delete(products);
            //db.SaveChanges();
            return RedirectToAction("Product", new { id = 1 });
        }

        [Authorize]
        public ActionResult PCreate()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult PCreate(string fProductName, string fProductCatagory, int fProductPrice)
        {
            //var pd = db.tProduct.Where(m => m.fProductName == fProductName).FirstOrDefault();
            var pd = _productRepository.GetByName(fProductName);
            if (pd != null)
            {
                ViewBag.IsProduct = true;
                return View();
            }
            string PID = "P";
            //var pCount = db.tProduct.ToList().Count();

MVC_FinalDemo/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_FinalDemo.Models;
using MVC_FinalDemo.Models.Interface;
using MVC_FinalDemo.Models.Repository;

namespace MVC_FinalDemo.Controllers
{
    public class CartsController : Controller
    {
        private ICartRepository _cartRepository;
        private IOrderRepository _orderRepository;
        private IOrderDetailRepository _orderDetailRepository;
        private IProductRepository _productRepository;
        public CartsController()
        {
            _cartRepository = new CartRepository();
            _orderRepository = new OrderRepository();
            _orderDetailRepository = new OrderDetailRepository();
            _productRepository = new ProductRepository();
        }
        //dbEStoreEntities db = new dbEStoreEntities();
        // GET: Carts
        [Authorize]
        public ActionResult Index()
        {
            //var usr = User.Identity.Name;
            //var carts = db.tCart.Where(m => m.fCustomerName == usr).ToList();
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Index(string custName, string custPhone, string custMail)
        {
            var usr = User.Identity.Name;
            //var Index = db.tOrder.ToList().LongCount();
            var Index = _orderRepository.GetAll().LongCount();
            var orderId = "OD" + Index + usr;
            tOrder odr = new tOrder()
            {
                fOrderID = orderId,
                fCustomerName = custName,
                fCustomerPhone = custPhone,
                fCustomerEmail = custMail,
                fDate = DateTime.Now.Date.ToString(),
                fState = "未出貨"
            };
            //db.tOrder.Add(odr);
            _orderRepository.Create(odr);
            //var carts = db.tCart.Where(m => m.fCustomerName == usr).ToList();
            var carts = _cartRepository.GetByName(usr).ToList();
            foreach (var item in carts)
            {
                //var product = db.tProduct.Where(m => m.fProductName == item.fProductName).FirstOrDefault();
                var product = _productRepository.GetByName(item.fProductName);
                tOrderDetail odd = new tOrderDetail()
                {
                    fOrderID = orderId,
                    fProductID = product.fProductID,
                    fProductName = item.fProductName,
                    fProductCount = item.fProductCount,
                    fProductPrice = item.fProductPrice,
                    fTotalPrice = item.fTotalPrice
                };
                //db.tOrderDetail.Add(odd);
                _orderDetailRepository.Create(odd);
            }
            //db.tCart.RemoveRange(carts);
            _cartRepository.DeleteRange(carts);
            //db.SaveChanges();
            return RedirectToAction("OrderInform", "Store");
        }
    }
}

MVC_FinalDemo/Views/Shared/Patrials/AdminNavPatrialView.cshtml
@*管理員Navbar*@

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
        @Html.ActionLink("金價宿大賣場", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
        <button type="button" data-toggle="collapse" data-target="#menu" class="navbar-toggler">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="menu" class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item">@Html.ActionLink("產品管理", "Product", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("類別管理", "Category", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("會員管理", "Member", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("訂單管理", "Order", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("登出", "Logout", "Member", new { area = "" }, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </div>
</nav>

MVC_FinalDemo/Views/Shared/Patrials/CarouselPatrialView.cshtml
<div class="carousel slide" data-ride="carousel" id="carouselLink">
    <ul class="carousel-indicators">
        <li data-target="#carouselLink" data-slide="0" class="active"></li>
        <li data-target="#carouselLink" data-slide="1"></li>
        <li data-target="#carouselLink" data-slide="2"></li>
        <li data-target="#carouselLink" data-slide="3"></li>
    </ul>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/banner/banner01.JPG" class="w-100" />
            <div class="carousel-caption">
                <h3>線上直播</h3>
                <p>線上直播課程，授課學習零距離接觸</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/banner/banner02.JPG" class="w-100" />
            <div class="carousel-caption">
                <h3>實體課程</h3>
                <p>實體課程，王牌名師親授超級技巧</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/banner/banner03.JPG" class="w-100" />
            <div class="carousel-caption">
                <h3>前後端整合</h3>
                <p>前端、後端、APP、雲端、資料層一次整合實作完成系統</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/banner/banner04.JPG" class="w-100" />
            <div class="carousel-caption">
                <h3>跨界整合</h3>
                <p>IT、餐飲、零售、醫療系統整合雲端，最實務系統建置課程</p>
            </div>
        </div>
    </div>
    <a href="#carouselLink" class="carousel-control-prev" data-slide="prev" role="button">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    </a>
    <a href="#carouselLink" class="carousel-control-next" data-slide="next" role="button">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>

MVC_FinalDemo/Views/Shared/Patrials/MamberNavPatrialView.cshtml
@*一般會員Navbar*@

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
        @Html.ActionLink("金價宿大賣場", "Index", "Store", new { area = "" }, new { @class = "navbar-brand" })
        <button type="button" data-toggle="collapse" data-target="#menu" class="navbar-toggler">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="menu" class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item">@Html.ActionLink("產品資料", "Detail", "Store", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("修改基本資料", "Edit", "Member", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("購物車資訊", "Index", "Carts", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item ">@Html.ActionLink("訂單資訊", "OrderInform", "Store", new { area = "" }, new { @class = "nav-link " })</li>
                <li class="nav-item">@Html.ActionLink("登出", "Logout", "Member", new { area = "" }, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </div>
</nav>

MVC_FinalDemo/Views/Shared/Patrials/NavPatrialView.cshtml
@*未登入的NavBar*@

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
        @Html.ActionLink("金價宿大賣場", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button type="button" data-toggle="collapse" data-target="#menu" class="navbar-toggler">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="menu" class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item">@Html.ActionLink("產品資料", "Detail", "Store", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("會員註冊", "Register", "Member", new { area = "" }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("登入系統", "Login", "Member", new { area = "" }, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </div>
</nav>